function TermsAndConditions() {
  return (
    <div>
      <h3 className="text-xl font-semibold mb-4 text-gray-900 dark:text-gray-100">Terms & Conditions</h3>
      <div className="space-y-4 text-gray-700 dark:text-gray-300">
        <p>
          <strong>Last Updated:</strong> October 31, 2025
        </p>
        
        <section>
          <h4 className="font-semibold mb-2 text-gray-900 dark:text-gray-100">Acceptance of Terms</h4>
          <p>
            By accessing and using SecLens, you accept and agree to be bound by the terms and provision of this agreement. 
            If you do not agree to these terms, please do not use SecLens.
          </p>
        </section>

        <section>
          <h4 className="font-semibold mb-2 text-gray-900 dark:text-gray-100">Service Description</h4>
          <p>
            SecLens is a free web application that provides on-demand security analysis for public GitHub repositories. 
            The service:
          </p>
          <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
            <li>Analyzes public GitHub repositories for security vulnerabilities</li>
            <li>Provides security reports and recommendations</li>
            <li>Allows users to download reports in multiple formats</li>
            <li>Does not store or persist any analysis results</li>
          </ul>
        </section>

        <section>
          <h4 className="font-semibold mb-2 text-gray-900 dark:text-gray-100">Use of Service</h4>
          <p>You agree to use SecLens only for lawful purposes and in accordance with these Terms. You agree not to:</p>
          <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
            <li>Use the service to analyze repositories you do not have permission to analyze</li>
            <li>Attempt to abuse, overload, or disrupt the service</li>
            <li>Use automated tools to make excessive requests</li>
            <li>Use the service for any illegal or unauthorized purpose</li>
          </ul>
        </section>

        <section>
          <h4 className="font-semibold mb-2 text-gray-900 dark:text-gray-100">Limitations of Service</h4>
          <p>
            SecLens is provided "as is" without warranties of any kind. We do not guarantee:
          </p>
          <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
            <li>Accuracy or completeness of security analysis reports</li>
            <li>Detection of all security vulnerabilities</li>
            <li>Continuous availability or uptime</li>
            <li>Performance characteristics for any specific repository</li>
          </ul>
        </section>

        <section>
          <h4 className="font-semibold mb-2 text-gray-900 dark:text-gray-100">Rate Limiting</h4>
          <p>
            To ensure fair usage and prevent abuse, SecLens implements rate limiting on API requests. 
            Excessive requests may result in temporary restrictions. We reserve the right to modify rate limits at any time.
          </p>
        </section>

        <section>
          <h4 className="font-semibold mb-2 text-gray-900 dark:text-gray-100">Intellectual Property</h4>
          <p>
            The SecLens application, including its design, code, and functionality, is protected by intellectual property laws. 
            Analysis reports generated by SecLens are provided to you for your use, but the underlying analysis methodology 
            and technology remain our property.
          </p>
        </section>

        <section>
          <h4 className="font-semibold mb-2 text-gray-900 dark:text-gray-100">Disclaimer of Warranties</h4>
          <p>
            SecLens is provided on an "as is" and "as available" basis. We make no representations or warranties of any kind, 
            express or implied, regarding the operation of the service or the information, content, or materials provided through it.
          </p>
        </section>

        <section>
          <h4 className="font-semibold mb-2 text-gray-900 dark:text-gray-100">Limitation of Liability</h4>
          <p>
            In no event shall SecLens or its operators be liable for any indirect, incidental, special, consequential, or punitive 
            damages arising out of your use of or inability to use the service.
          </p>
        </section>

        <section>
          <h4 className="font-semibold mb-2 text-gray-900 dark:text-gray-100">Modifications to Terms</h4>
          <p>
            We reserve the right to modify these Terms & Conditions at any time. Continued use of SecLens after such modifications 
            constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h4 className="font-semibold mb-2 text-gray-900 dark:text-gray-100">Contact</h4>
          <p>
            For questions about these Terms & Conditions, please contact us through our GitHub repository.
          </p>
        </section>
      </div>
    </div>
  )
}

export default TermsAndConditions

